---
- name: Install Ansible
  vars_prompt:
   hosts: "Please enter hosts group name"
  hosts: $hosts
  sudo: yes
  tasks:
  - name: Update cache
    apt: update_cache=yes
  - name: Install ansible
    apt:  pkg=ansible state=present
