---
 - hosts: logs
   sudo: yes
   tasks:
   - name: Upgrade OS
     apt: update_cache=yes
     apt: upgrade=dist
     sudo: yes
   - name: Install Java
     apt: pkg=openjdk-7-jre-headless state=latest
   - name: Install Mongo
     apt: pkg=mongodb-server state=latest
   - name: Install uuid-runtime
     apt: pkg=uuid-runtime state=latest
   - name: Install adduser
     apt: pkg=adduser state=latest
   - name: Download Elasticsearch
     get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.10.deb dest=/home/level15/elasticsearch-0.90.10.deb
   - name: Install Elasticsearch
     command: dpkg -i elasticsearch-0.90.10.deb
   - name: Copy config file for elasticsearch
     copy: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
   - name: Restart Elasticsearch
#     service: name=elasticsearch state=restarted
     command: /etc/init.d/elasticsearch restart
   - name: Download Graylog2 Server
     get_url: url=http://finja.brachium-system.net/%7Ejonas/packages/graylog2/graylog2-server_0.20.0~rc.1.1-1_all.deb dest=/home/level15/graylog2-server_0.20.0~rc.1.1-1_all.deb
   - name: Download Graylog2 Web
     get_url: url=http://finja.brachium-system.net/%7Ejonas/packages/graylog2/graylog2-web_0.20.0~rc.1.1-1_all.deb dest=/home/level15/graylog2-web_0.20.0~rc.1.1-1_all.deb
   - name: Install Graylog2 Server
     command: dpkg -i graylog2-server_0.20.0~rc.1.1-1_all.deb
   - name: Install Graylog2 Web
     command: dpkg -i graylog2-web_0.20.0~rc.1.1-1_all.deb
   - name: Enable init script for Graylog2 Serve
     command: sed -i 's@no@yes@' /etc/default/graylog2-server
   - name: Enable init script for Graylog2 Web
     command: sed -i 's@no@yes@' /etc/default/graylog2-web
   - name: Copy config file for Graylog2 Server
     copy: src=server.conf dest=/etc/graylog2/server/server.conf
   - name: Copy config file for Graylog2 Server Elasticsearch
     copy: src=graylog2-elasticsearch.yml dest=/etc/graylog2/server/graylog2-elasticsearch.yml
   - name: Copy config file for Graylog2 Web
     copy: src=graylog2-web-interface.conf dest=/etc/graylog2/web/graylog2-web-interface.conf
   - name: Copy config file for syslog
     copy: src=rsyslog.conf dest=/etc/rsyslog.conf
   - name: Restart rsyslog
     service: name=rsyslog state=restarted
#   - name: Start Graylog2 Server
#     service: name=graylog2-server state=restarted
#   - name: Start Graylog2 Web
#     service: name=graylog2-web state=restarted
   - name: Start Graylog2 Server
     command: /etc/init.d/graylog2-server start
   - name: Restart Graylog2 Server
     command: /etc/init.d/graylog2-server restart
   - name: Start Graylog2 Server
     command: /etc/init.d/graylog2-server start
   - name: Start Graylog2 Web
     command: /etc/init.d/graylog2-web start
