---
- hosts: test
  sudo: yes
  tasks:
  - name: Update cache
    apt: update_cache=yes
  - name: Install module pycurl
    apt:  pkg=python-pycurl state=present
  - name: Add repository with Zabbix 2.2
    command: wget http://repo.zabbix.com/zabbix/2.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_2.2-1+precise_all.deb
  - name: Install repo
    command: dpkg -i zabbix-release_2.2-1+precise_all.deb
  - name: Update cache
    apt: update_cache=yes
  - name: Install zabbix agent
    apt: pkg=zabbix-agent state=present
  - name: Add zabbix_agentd.conf
    copy: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf force=yes owner=root group=root mode=644 backup=yes
  - name: Restart zabbix agent
    service: name=zabbix-agent state=restarted
