---
- name: Upgrade server

  vars_prompt:
    hosts: "Please enter hosts group name"

  hosts: $hosts 
  sudo: yes

  tasks:
  - name: Upgrade OS
    apt: update_cache=yes
    apt: upgrade=dist
    sudo: yes
  - name: Reboot the server
    command: reboot
