---
- hosts: logs
  sudo: yes
  tasks:
  - name: Change Hostname to localhost name
    lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp='^#Hostname=' line='Hostname={{ansible_hostname}}'
  - name: Restart zabbix agent
    service: name=zabbix-agent state=restarted
