---
- hosts: custom
  sudo: yes
  tasks:
  - name: Upgrade OS
    apt: update_cache=yes
    apt: upgrade=dist
    sudo: yes
  - name: Install wget
    apt: pkg=wget state=present
  - name: Install vim
    apt: pkg=vim state=present
  - name: Install perl
    apt: pkg=perl state=present
  - name: Install ntpdate
    apt: pkg=ntpdate state=present
  - name: Install mlocate
    apt: pkg=mlocate state=present
  - name: Install fail2ban
    apt: pkg=fail2ban state=present
  - name: Change DHCP settings
    copy: src=dhclient.conf dest=/etc/dhcp/dhclient.conf force=yes owner=root group=root mode=644 backup=yes
  - name: Change hostname
    copy: src=hostname dest=/etc/hostname force=yes owner=root group=root mode=644 backup=yes
  - name: Restart network
    service: name=networking state=restarted
  - name: Install banner EPAM
    get_url: url=ftp://epbyminsd0094.minsk.epam.com/banner.epam dest=/etc/ssh/
  - name: Copy config file for ssh
    copy: src=sshd_config dest=/etc/ssh/ force=yes owner=root group=root mode=0644 backup=yes 
  - name: Set update time in cron
    cron: name="Update time" minute="30" job="/usr/sbin/ntpdate -u 10.6.0.6" user="root"
  - name: Add user level15
    user: name=level15 comment="EPAM Cloud Support user" group="users" groups="sudo" shell="/bin/bash"
  - name: Add user maintenance
    user: name=maintenance comment="Support DEV SRV MSQ user" group="users" groups="sudo" shell="/bin/bash"
  - name: Add user level15
    user: name=level15 comment="User for security check" group="users" groups="sudo" shell="/bin/bash"
  - name: Reboot the server
    command: reboot

